[tool.poetry]
name = "pyamber"
version = "0.0.0"
description = "Interact with Amber"
authors = ["Thomas Schmelzer"]
readme = "README.md"
packages = [{include = "pyamber"}]

[tool.poetry.dependencies]
python = ">=3.9"
requests = "*"
pandas = "^2.0.0"
flask = "*"

[tool.poetry.dev-dependencies]
pytest = "7.4.0"
pytest-cov = "*"
httpretty = "*"
pytest-html = "*"
requests-mock = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "I"]
line-length = 120
target-version = "py310"
exclude = [
    "*__init__.py"
]
