name: "book"

on:
  push

jobs:
  pdoc:
    runs-on: "ubuntu-latest"  
    steps:
      - uses: cvxgrp/.github/actions/uv/pdoc@main
        with:
          source-folder: "pyamber"


  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/uv/coverage@main
        with:
          source-folder: "pyamber"


  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/uv/jupyter@main


  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@main
