name: "book"

on:
  push

jobs:
  sphinx:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/sphinx@v1.1.0

  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/coverage@v1.1.0

  book:
    runs-on: "ubuntu-latest"
    needs: [test, sphinx]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v1.1.0
