name: "book"

on:
  push

jobs:
  pdoc:
    steps:
      - uses: cvxgrp/.github/actions/uv/pdoc@main
        with:
          source-folder: "pyamber"


  test:
    steps:
      - uses: cvxgrp/.github/actions/uv/coverage@main
        with:
          source-folder: "pyamber"

  book:
    needs: [test, pdoc]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@main
