name: "book"

on:
  push:
    branches:
      - main

jobs:
  pdoc:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.75

      - uses: tschm/cradle/actions/pdoc@v0.1.75
        with:
          source-folder: 'pyamber'

  test:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.75

      - uses: tschm/cradle/actions/coverage@v0.1.75
        with:
          source-folder: 'pyamber'
          tests-folder: 'tests'

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc]

    permissions:
      contents: read
      id-token: write
      pages: write

    environment:
      name: github-pages

    steps:
      - uses: tschm/cradle/actions/book@v0.1.75
        with:
          title: "amberdata"
          links: |
            {
              "API": "./pdoc/index.html"
            }
