name: pre-commit

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: cvxgrp/.github/actions/uv/coverage@main
      with:
        source-folder: 'pyamber'

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
      with:
        files: artifacts/tests/coverage/coverage.info
        format: lcov
